#include "pt_defs.h"

/* NOTE!!!!!!!
 * THIS MUST STAY HARDCODED AS PT_PRODUCT_DSPFX.
 * IT IS ACTUALLY OUTDATED AND REFERENCES TO PT_PRODUCT_TYPE
 * SHOULD BE REMOVED FROM CODE.
 */
#define PT_PRODUCT_TYPE PT_PRODUCT_DSPFX
